"""Register profile: SRNE Energy Storage Inverter Modbus protocol V1.7.

Covers SRNE HYP-series hybrid inverter/chargers and rebrands thereof
(e.g. Sungold SPH series). This is data, not logic — additional profiles
for other SRNE product families (e.g. the standalone ML/MT charge
controller protocol) can be added as sibling files in this `profiles/`
package without touching the coordinator, platform, or config flow code.

Each entry in REGISTERS is a dict describing one logical value. Multi-register
(32-bit) values use "length": 2 and "data_type": "uint32"/"int32".

Field reference:
  key          - stable internal id, used to build unique_id and lookups
  name         - friendly name (device name is prepended by the entity layer)
  address      - starting register address (int, not hex string)
  length       - number of 16-bit registers (1 unless noted)
    data_type    - "uint16" | "int16" | "uint32" | "int32"
  access       - "r" (read-only) or "rw" (writable holding register)
  entity       - "sensor" | "number" | "select" | "binary_sensor"
  scale        - multiply raw register value by this to get the real value
  unit         - unit_of_measurement, or None
  device_class - HA device_class string, or None
  min_value / max_value - for "number" entities; enforced both in entity
                 bounds and in the coordinator's write guard. Values are in
                 real (scaled) units, not raw register units.
  step         - for "number" entities, UI step size in real units
  options      - for "select" entities: dict of {raw_int_value: label}
  category     - grouping used only for dashboard/UI organization
                 ("telemetry", "battery_config", "inverter_config")
"""

from __future__ import annotations

PROFILE_ID = "srne_esi_v1_7"
PROFILE_NAME = "SRNE Energy Storage Inverter (V1.7) — HYP series / rebrands"

DEFAULT_SLAVE_ID = 1

# --- Enum option tables, defined once and reused ---

CHARGE_STATE_OPTIONS = {
    0: "Off",
    1: "Quick charge",
    2: "Constant voltage",
    4: "Float",
    6: "Li battery activate",
}

MACHINE_STATE_OPTIONS = {
    0: "Power-up delay",
    1: "Waiting",
    2: "Initialization",
    3: "Soft start",
    4: "Mains powered",
    5: "Inverter powered",
    6: "Inverter to mains",
    7: "Mains to inverter",
    8: "Battery activate",
    9: "Shutdown by user",
    10: "Fault",
}

BATTERY_TYPE_OPTIONS = {
    0: "User defined",
    1: "Sealed lead-acid (SLD)",
    2: "Flooded lead-acid (FLD)",
    3: "Gel",
    4: "Lithium (BMS-less / voltage profile)",
}

CHARGE_PRIORITY_OPTIONS = {
    0: "PV preferred (mains only if PV unavailable)",
    1: "Mains preferred (PV only if mains unavailable)",
    2: "Hybrid (PV + mains simultaneously, PV preferred)",
    3: "PV only (mains never charges)",
}

OUTPUT_PRIORITY_OPTIONS = {
    0: "Solar",
    1: "Line (mains)",
    2: "SBU (Solar-Battery-Utility)",
}

AC_INPUT_RANGE_OPTIONS = {
    0: "Wide range (APL)",
    1: "Narrow range (UPS)",
}

ENABLE_DISABLE_OPTIONS = {
    0: "Disable",
    1: "Enable",
}

REGISTERS: list[dict] = [
    # ===================== Telemetry (read-only) =====================
    {
        "key": "battery_soc",
        "name": "Battery SOC",
        "address": 0x0100,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": "%",
        "device_class": "battery",
        "category": "telemetry",
    },
    {
        "key": "battery_voltage",
        "name": "Battery Voltage",
        "address": 0x0101,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "category": "telemetry",
    },
    {
        "key": "battery_current",
        "name": "Battery Current",
        "address": 0x0102,
        "length": 1,
        "data_type": "int16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "category": "telemetry",
    },
    {
        "key": "device_temp_raw",
        "name": "Device Temperature (raw, packed)",
        "address": 0x0103,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "category": "telemetry",
        "enabled_by_default": False,
        "note": "High byte = controller temp C, low byte = battery temp C. "
        "Split into derived sensors by the sensor platform.",
    },
    {
        "key": "pv1_voltage",
        "name": "PV1 Voltage",
        "address": 0x0107,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "category": "telemetry",
    },
    {
        "key": "pv1_current",
        "name": "PV1 Current",
        "address": 0x0108,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "category": "telemetry",
    },
    {
        "key": "pv1_power",
        "name": "PV1 Power",
        "address": 0x0109,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "category": "telemetry",
    },
    {
        "key": "charge_state",
        "name": "Charge State",
        "address": 0x010B,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": None,
        "device_class": "enum",
        "options": CHARGE_STATE_OPTIONS,
        "category": "telemetry",
    },
    {
        "key": "charge_power_total",
        "name": "Charge Power (Total)",
        "address": 0x010E,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "category": "telemetry",
    },
    {
        "key": "pv_charge_current",
        "name": "PV Charge Current (battery side)",
        "address": 0x0224,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "category": "telemetry",
    },
    {
        "key": "machine_state",
        "name": "Machine State",
        "address": 0x0210,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": None,
        "device_class": "enum",
        "options": MACHINE_STATE_OPTIONS,
        "category": "telemetry",
    },
    {
        "key": "bus_voltage",
        "name": "Bus Voltage",
        "address": 0x0212,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "category": "telemetry",
        "enabled_by_default": False,
    },
    {
        "key": "grid_voltage",
        "name": "Grid Voltage",
        "address": 0x0213,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "category": "telemetry",
    },
    {
        "key": "grid_current",
        "name": "Grid Current",
        "address": 0x0214,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "category": "telemetry",
    },
    {
        "key": "grid_frequency",
        "name": "Grid Frequency",
        "address": 0x0215,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.01,
        "unit": "Hz",
        "device_class": "frequency",
        "category": "telemetry",
    },
    {
        "key": "inverter_output_voltage",
        "name": "Inverter Output Voltage",
        "address": 0x0216,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "category": "telemetry",
    },
    {
        "key": "inverter_output_current",
        "name": "Inverter Output Current",
        "address": 0x0217,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "category": "telemetry",
    },
    {
        "key": "inverter_frequency",
        "name": "Inverter Frequency",
        "address": 0x0218,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.01,
        "unit": "Hz",
        "device_class": "frequency",
        "category": "telemetry",
    },
    {
        "key": "load_current",
        "name": "Load Current",
        "address": 0x0219,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "category": "telemetry",
    },
    {
        "key": "load_active_power",
        "name": "Load Active Power",
        "address": 0x021B,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "category": "telemetry",
    },
    {
        "key": "load_apparent_power",
        "name": "Load Apparent Power",
        "address": 0x021C,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": "VA",
        "device_class": "apparent_power",
        "category": "telemetry",
    },
    {
        "key": "mains_charge_current",
        "name": "Mains Charge Current",
        "address": 0x021E,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "category": "telemetry",
    },
    {
        "key": "load_ratio",
        "name": "Load Ratio",
        "address": 0x021F,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": "%",
        "device_class": None,
        "category": "telemetry",
    },
    {
        "key": "heatsink_a_temp",
        "name": "Heatsink A Temperature",
        "address": 0x0220,
        "length": 1,
        "data_type": "int16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "°C",
        "device_class": "temperature",
        "category": "telemetry",
    },
    {
        "key": "heatsink_b_temp",
        "name": "Heatsink B Temperature",
        "address": 0x0221,
        "length": 1,
        "data_type": "int16",
        "access": "r",
        "entity": "sensor",
        "scale": 0.1,
        "unit": "°C",
        "device_class": "temperature",
        "category": "telemetry",
    },
    {
        "key": "fault_code_1",
        "name": "Fault Code 1",
        "address": 0x0204,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "category": "telemetry",
        "enabled_by_default": False,
    },
    {
        "key": "fault_code_2",
        "name": "Fault Code 2",
        "address": 0x0205,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "category": "telemetry",
        "enabled_by_default": False,
    },
    {
        "key": "fault_code_3",
        "name": "Fault Code 3",
        "address": 0x0206,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "category": "telemetry",
        "enabled_by_default": False,
    },
    {
        "key": "fault_code_4",
        "name": "Fault Code 4",
        "address": 0x0207,
        "length": 1,
        "data_type": "uint16",
        "access": "r",
        "entity": "sensor",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "category": "telemetry",
        "enabled_by_default": False,
    },
    # ===================== Battery config (writable) =====================
    {
        "key": "pv_charge_current_limit",
        "name": "PV Charge Current Limit",
        "address": 0xE001,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "min_value": 0,
        "max_value": 100,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "nominal_battery_capacity",
        "name": "Nominal Battery Capacity",
        "address": 0xE002,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 1,
        "unit": "Ah",
        "device_class": None,
        "min_value": 0,
        "max_value": 400,
        "step": 1,
        "category": "battery_config",
    },
    {
        "key": "battery_type",
        "name": "Battery Type",
        "address": 0xE004,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "select",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "options": BATTERY_TYPE_OPTIONS,
        "category": "battery_config",
    },
    {
        "key": "over_voltage_threshold",
        "name": "Over-voltage Threshold",
        "address": 0xE005,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
        "note": "Per 12V-equivalent battery block; multiply by series count for actual pack voltage.",
    },
    {
        "key": "limited_charge_voltage",
        "name": "Limited Charge Voltage",
        "address": 0xE006,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "equalizing_charge_voltage",
        "name": "Equalizing Charge Voltage",
        "address": 0xE007,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "boost_charge_voltage",
        "name": "Boost / Overcharge Voltage",
        "address": 0xE008,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
        "note": "Boost charge voltage for lead-acid; overcharge voltage for lithium.",
    },
    {
        "key": "floating_charge_voltage",
        "name": "Floating / Overcharge Recovery Voltage",
        "address": 0xE009,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
        "note": "May be a no-op when BMS Communication Enable is on; "
        "the BMS typically takes over charge-voltage decisions in that mode.",
    },
    {
        "key": "boost_charge_recovery_voltage",
        "name": "Boost Charge Recovery Voltage",
        "address": 0xE00A,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "over_discharge_recovery_voltage",
        "name": "Over-discharge Recovery Voltage",
        "address": 0xE00B,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "under_voltage_warning",
        "name": "Under-voltage Warning Level",
        "address": 0xE00C,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "over_discharge_voltage",
        "name": "Over-discharge Voltage",
        "address": 0xE00D,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "limited_discharge_voltage",
        "name": "Limited Discharge Voltage",
        "address": 0xE00E,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 9,
        "max_value": 15.5,
        "step": 0.1,
        "category": "battery_config",
    },
    {
        "key": "stop_charging_current",
        "name": "Stop Charging Current (Lithium tail-current cutoff)",
        "address": 0xE01C,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "min_value": 0,
        "max_value": 40,
        "step": 0.1,
        "category": "battery_config",
        "note": "Lithium only. Charging stops once current drops below this in constant-voltage stage.",
    },
    # ===================== Inverter config (writable) =====================
    {
        "key": "charge_priority",
        "name": "Charge Priority",
        "address": 0xE20F,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "select",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "options": CHARGE_PRIORITY_OPTIONS,
        "category": "inverter_config",
    },
    {
        "key": "output_priority",
        "name": "Output Priority",
        "address": 0xE204,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "select",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "options": OUTPUT_PRIORITY_OPTIONS,
        "category": "inverter_config",
    },
    {
        "key": "mains_charge_current_limit",
        "name": "Mains Charge Current Limit",
        "address": 0xE205,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "min_value": 0,
        "max_value": 100,
        "step": 0.1,
        "category": "inverter_config",
    },
    {
        "key": "max_charge_current",
        "name": "Max Charge Current (PV + Mains combined)",
        "address": 0xE20A,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "A",
        "device_class": "current",
        "min_value": 0,
        "max_value": 150,
        "step": 0.1,
        "category": "inverter_config",
    },
    {
        "key": "ac_input_range",
        "name": "AC Input Range",
        "address": 0xE20B,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "select",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "options": AC_INPUT_RANGE_OPTIONS,
        "category": "inverter_config",
    },
    {
        "key": "output_voltage",
        "name": "Output Voltage Setpoint",
        "address": 0xE208,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "min_value": 100,
        "max_value": 264,
        "step": 0.1,
        "category": "inverter_config",
    },
    {
        "key": "output_frequency",
        "name": "Output Frequency Setpoint",
        "address": 0xE209,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "number",
        "scale": 0.01,
        "unit": "Hz",
        "device_class": "frequency",
        "min_value": 45,
        "max_value": 65,
        "step": 0.01,
        "category": "inverter_config",
    },
    {
        "key": "bms_communication_enable",
        "name": "BMS Communication Enable",
        "address": 0xE215,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "select",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "options": ENABLE_DISABLE_OPTIONS,
        "category": "battery_config",
        "note": "When enabled, the inverter typically defers charge-voltage decisions "
        "to the BMS — the static voltage setpoints above (E005-E00B) may become no-ops. "
        "Verify against your specific BMS behavior after enabling.",
    },
    {
        "key": "equalizing_charge_enable",
        "name": "Equalizing Charge Enable",
        "address": 0xE206,
        "length": 1,
        "data_type": "uint16",
        "access": "rw",
        "entity": "select",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "options": ENABLE_DISABLE_OPTIONS,
        "category": "battery_config",
        "note": "Should generally remain Disabled for lithium batteries.",
    },
]


def get_register(key: str) -> dict | None:
    """Look up a single register definition by its key."""
    for reg in REGISTERS:
        if reg["key"] == key:
            return reg
    return None


def registers_by_entity(entity_type: str) -> list[dict]:
    """Return all register definitions for a given entity platform type."""
    return [r for r in REGISTERS if r["entity"] == entity_type]
